@startuml Manage Bill

title Manage Bill 

actor Customer
actor Cashier
box System
    entity Interface
    database "Order List" as Orders
end box

activate Customer

Customer -> Interface ++ : Pay bill
alt Cash
    Interface -> Cashier ++ : Notify
    Customer -> Cashier: Give cash
    alt Has changes
        Cashier --> Customer: Return changes
    end
    Cashier -> Interface: Update status
    Interface --> Cashier : Response
    Cashier --> Customer -- : Response
else E-Wallet / online banking
    Customer -> Interface: Make payment
    Interface -> Interface: Check payment
    Interface -> Interface: Update status
    Interface --> Customer: Response
end

Interface -> Orders ++ : Update order
Orders -> Orders: Delete order
return Response

alt Request physical receipt
    Customer -> Cashier ++ : Request receipt
    Cashier -> Cashier: Open receipt
    return Receipt
else Request digital receipt
    Customer -> Interface: Request receipt
    Interface -> Interface: Generate receipt
    return Receipt
end

deactivate Customer

@enduml