@startuml

scale 5

hide circle

entity OrderSystem {
  +**order_id**: INTEGER
  ---
  +quantity: INTEGER
  +order_total: DECIMAL
  +order_status: VARCHAR(20)
  +customer_name: VARCHAR(50)
  +customer_email: VARCHAR(100)
  +customer_phone: VARCHAR(20)
  +product_name: VARCHAR(100)
  +product_price: DECIMAL
  +product_stock: INTEGER
  +vendor_name: VARCHAR(100)
  +vendor_contact_name: VARCHAR(50)
  +vendor_email: VARCHAR(100)
  +vendor_phone: VARCHAR(20)
  +note_content: VARCHAR(500)
}

@enduml
