@startuml Manage Order

title Manage Order

actor "Customer /\nWaiter /\nCashier" as Maker
actor Chef
box System

    participant Order
    participant "Food List" as Foods
    participant "Order List" as Orders
end box

activate Maker

alt Request Menu
    Maker -> Foods ++ : Get menu

    
    return Menu
    |||
    Foods -> Foods : Render menu
    return Menu
end

|||



Maker -> Order ** : <<Create Order>>
Maker -> Order ++ : Make order
activate Order

Order -> Order: Set metadata

loop Order not confirmed
    alt Modify order
        Maker -> Order: Modify order

        alt Add food
            Maker -> Order: Add food
        else Remove food
            Maker -> Order: Remove food
        end

        Order -> Order: Update order
    else Confirm order
        Maker -> Order: Confirm order
            
                Order -> Orders ++ : Order
                    Orders -> Orders : Update order list
                return Response
            Order -->  Chef: Notify
        Order --> Maker: Response
    else Cancel order
        Maker -> Order: Cancel Order
        
        Order -> Order !! : <<Destroy Order>>
        return Order Canceled
        deactivate Order

        
    end
end

deactivate Maker

@enduml