@startuml Prepare Food

title Prepare Food

actor Chef
actor "Waiter / Cashier" as Useless
box System
    participant Interface
    participant "Food List" as Foods
    participant "Order List" as Orders
end box

note left Interface: System received new order
activate Interface
Interface --> Chef ++ : Notify  
alt Low stock
    Chef -> Interface: Update menu availability 
    Interface -> Foods ++ : Update menu
    return Response
end
Chef -> Interface: Get order
Interface -> Orders ++ : Get order
return Order
Interface --> Chef: Order

|||

loop for each food in Order
    note left Orders: Update order status
    Chef -> Interface -- : Complete order
    Interface -> Orders ++ : Update
    return Response

    Interface -> Useless ++ : Notify
    Return Update
    Interface -> Orders ++ : Update
    return Response
end

@enduml